version: '3.1'

services:
  gomongo:
    container_name: gomongo
    build: 
      context: ../
      dockerfile: Dockerfile.production
    env_file: 
      - ../configs/dev.env
    depends_on: 
      - mongo
    ports: 
      - 8080:8080
    volumes: 
      - .:/app
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/